- .devcontainer/devcontainer.json
- .vscode/launch.json
* devcontainer with Node 22 that NPM installs the `/client/`
* launch.json with a script to start Nuxt
> chore: devcontainer

- .devcontainer/devcontainer.json
- client/assets/css/tailwind.css
- client/components/Alert.vue
- client/components/Card.vue
- client/components/ContentBreadcrumbs.vue
- client/components/ContentDocLastUpdated.vue
- client/components/Footer.vue
- client/components/Graphics/Diamond.vue
- client/components/Header.vue
- client/components/Heading.vue
- client/components/IndexSubheader.vue
- client/components/RFCCard.vue
- client/components/RFCDocumentBody.vue
- client/components/RFCDocumentSidebar.vue
- client/components/RFCMobileBanner.vue
- client/components/Renderable.vue
- client/components/SectionHeader.vue
- client/components/Tag.vue
- client/content/about.md
- client/content/about/subpub_stats.md
- client/content/test.md
- client/package-lock.json
- client/pages/[...slug].vue
- client/pages/search.vue
- client/scripts/generate-content-metadata.ts
- client/tailwind.config.js
* print css
and tidy ups to
* upgrading package.json deps
* devcontainer (for nuxt dev server also proxy websockets)
* markdown content breadcrumbs and 'last modified' footer
* adding renderable.vue to simplify rendering of strings vs components
> feat: print css and misc fixes

- client/nuxt.config.ts
- client/redirects.json
- client/server/routes/search/rfc_search_detail.php.ts
* redirects a few more legacy routes using [`routeRules`](https://nitro.build/config#routerules)
> feat: Legacy redirects (2)

- README.md
Adding a link to Figma so that people know what design we're adhering to.
> feat: Link to graphic design of new site

- CHANGELOG.md
> feat: Changelog.md

- k8s/rfced-www.yaml
Adds access to the secrets now made available on deployment
> ci: secrets for k8s deployment

- client/pages/index.vue
- client/stores/search.ts
None of these `splice` usages look problematic but I'll add some additional safety checks anyway.
> chore: Splice

- client/components/AMaybeRFCLink.vue
- client/components/content/ProseA.vue
- client/components/content/ProseH1.vue
- client/utilities/redClientWrappers.ts
- client/utilities/redirects.ts
* ensuring redClientWrapper is only called serverside and adding more debug
* removing debug from ProseH1
* fixing docstring formatting
* fixing anchor links
> chore: redClientWrapper.ts only server and misc tidy

- client/components/RFCIndexPage.vue
* move apiclient to `useAsyncData` so it's serverside-only
> fix: Only use apiclient on server

- client/stores/search.ts
> fix: only search on search

- client/pages/index.vue
Fixes hydration errors / glitches
> fix: computed() for reactivity on index page

- client/pages/search.vue
* `UIState` was out of sync with JS usage
> fix: UIState type out of sync

- client/components/Alert.vue
- client/components/Card.vue
- client/components/Heading.vue
- client/components/RFCCard.vue
- client/components/RFCCardBody.vue
- client/components/RFCCardCompact.vue
- client/components/RFCCardDense.vue
- client/components/RFCCardTypeSenseItem.vue
- client/components/SearchMobileFilter.vue
- client/components/SearchSortBy.vue
- client/pages/search.vue
- client/utilities/html.ts
- client/utilities/typesense.ts
* search card density and design
> feat: Search card density and design

- client/components/HorizontalScrollable.vue
- client/pages/search.vue
* This PR fixes TS issues on `main`. I guess the [semver changes](https://github.com/ietf-tools/red/commit/152b3c297f6ba392857f49a5ef52a1453d1914be) pulled in a different version which changed the typing enough to cause problems
> Chore: fixing TS issues on main

- client/components/TableOfContentsMarkdownDesktop.vue
* design fixes to markdown toc pages
> fix: markdown toc fixes

- client/assets/css/rfc-plaintext.css
- client/components/RFCRouterLink.vue
- client/components/TableOfContentsHighlight.vue
- client/components/TableOfContentsHighlightSection.vue
- client/generated/red-client.ts
- client/nuxt.config.ts
- client/pages/info/[id].vue
- client/utilities/dom.ts
- client/utilities/red-rfc-html-extractor/index.ts
- client/utilities/red-rfc-html-extractor/plaintext.ts
- client/utilities/red-rfc-html-extractor/xml2rfc.ts
- client/utilities/scroll.ts
- client/utilities/tableOfContents.ts
* scrape plaintext TOC mimicing [this datatracker algo](https://github.com/ietf-tools/datatracker/blob/2bf633bf70c40b9cb6baf428901615a0403e1ea5/ietf/static/js/nav.js#L24)
* styles plaintext RFC links as blue
* refactor scraping code to be distinct per RFC html generator
**screenshot**
> feat: plaintext toc

- client/components/RFCDocumentBody.vue
* add 'title' to rfc info page
* fix errata number bug (was showing PK instead of rfc number)
> feat: RFC info page title and errata number fix

- client/assets/css/rfc-plaintext.css
- client/assets/css/upstream-xml2rfc.css
- client/assets/css/xml2rfc-darkmode-patches.css
- client/components/AMaybeRFCLink.vue
- client/components/Breadcrumbs.vue
- client/components/HorizontalScrollable.vue
- client/components/RFCCardBody.vue
- client/components/RFCDocumentBody.vue
- client/components/RFCDocumentBodyPill.vue
- client/components/RFCDocumentSidebar.vue
- client/components/RFCMobileBanner.vue
- client/components/RFCTabs.vue
- client/components/TableOfContents.vue
- client/components/TableOfContentsSection.vue
- client/components/content/ProsePre.vue
- client/utilities/dom.ts
- client/utilities/red-rfc-html-extractor-shared/xml2rfc.ts
- client/utilities/rfc.ts
- client/utilities/tableOfContents.ts
- client/utilities/theme.ts
- client/utilities/url.test.ts
- client/utilities/url.ts
* HTML RFC fixes (design, dark mode, etc.)
> feat: HTML RFC fixes (design, dark mode, etc)

- client/app/assets/css/upstream-xml2rfc.css
- client/app/components/RFCRouterLink.vue
- client/app/components/RFCRouterLinkPreview.vue
- client/app/utilities/scroll.ts
- client/app/utilities/url.test.ts
- client/app/utilities/url.ts
* vue hydration errors caused by different logic between server and client depending on `window.location`. This was used to resolve `href`s` but now we just do janky string comparison.
* rfc html formatting for `<address>` sections etc
> fix: vue hydration errors. rfc html formatting

- client/app/assets/css/upstream-xml2rfc.css
- client/app/components/RFCCardBody.vue
- client/app/components/RFCDocumentBody.vue
- client/app/components/RFCTabs.vue
- client/app/utilities/rfc.test.ts
- client/app/utilities/rfc.ts
- client/package-lock.json
- client/package.json
* errata diamond only shown if there's errata (currently there's none due to API issues)
* `<dd>` list indentation
* centralise isAprilFools logic
* add icon pack
> fix: RFC info page misc fixes

- client/app/components/RFCDocument.vue
- client/app/utilities/rfc-validators.ts
* Add PDF support from `red-rfc-html-extractor`
> feat: pdf RFCs

- client/app/components/HorizontalScrollable.vue
- client/app/components/PdfPages.vue
- client/app/components/RFCDocumentBody.vue
- client/app/components/ScrollToTop.vue
* Improved PDF responsive behaviour (min/max width)
* Show 'scroll to top' after only scrolling 250px
> feat: pdf responsive behaviour

- .github/workflows/rfc-html-extractor-build.yml
- rfc-html-extractor/src/cron.ts
- rfc-html-extractor/src/tasks/rfc-index-txt.ts
- rfc-html-extractor/src/tasks/rfc-index-xml.ts
> fix: rfc-index.xml

- client/app/utilities/rfc-converter-parse.ts
- client/app/utilities/rfc-validators.ts
- rfc-html-extractor/src/tasks/rfc-index-xml.ts
* improving parsing/types for related props
* docstring FIXME for behaviour we should review before launch
> chore: refactoring tidy up. docstrings

- rfc-html-extractor/src/cron.ts
- rfc-html-extractor/src/single.ts
* worker cron.ts now runs as a Node script
> fix: cron worker

- client/modules/analytics-matomo/index.ts
- client/modules/analytics-matomo/runtime/client.ts
> feat: analytics matomo

- client/app/components/RFCRouterLink.vue
- client/app/components/RFCRouterLinkPreview.vue
- client/app/utilities/analytics-matomo.ts
- client/modules/analytics-matomo/index.ts
- client/modules/analytics-matomo/runtime/client.ts
* Matomo analytics for SPA page views
* Matomo analytics for RFC Link previews
> feat: Matomo events

- client/app/utilities/analytics-matomo.ts
- client/modules/analytics-matomo/runtime/client.ts
> fix: track spa page views

- client/app/components/RFCDocument.vue
- client/app/utilities/url.ts
* although SPA nav to `/info/rfc*/` would work the server rendered page would 404. This fixes that. See also one-liner change to Cloudflare config to set the correct JSON Content-Type.
> fix: RFC HTML document loading

- client/package-lock.json
- client/package.json
> chore: nuxt 4.1.3 upgrade

- README.md
> chore: README.md fixes

- client/app/components/FooterNavData.ts
*  remove translation links. they will be inserted on markdown page
> chore: remove translation links. they will be inserted on markdown page
